### ISSUE TITLE
migrate_old_shipping_calculators migration from spree errors with the spree_active_shipping Calculators.

### ISSUE THREAD

**Issue by FineLineAutomation** [spree-contrib/spree_active_shipping#169]
```
==  MigrateOldShippingCalculators: migrating ==================================
rake aborted!
An error has occurred, this and all later migrations canceled:

The single-table inheritance mechanism failed to locate the subclass: 'Spree::Calculator::Ups::ThreeDaySelect'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite 
Spree::Calculator.inheritance_column to use another column for that information./Users/nate/Projects/Websites/spree-fine-line-automation/db/migrate/20131215195190_migrate_old_shipping_calculators.spree.rb:5:in `block in up'
/Users/nate/Projects/Websites/spree-fine-line-automation/db/migrate/20131215195190_migrate_old_shipping_calculators.spree.rb:4:in `each'
/Users/nate/Projects/Websites/spree-fine-line-automation/db/migrate/20131215195190_migrate_old_shipping_calculators.spree.rb:4:in `up'
/Users/nate/.rvm/gems/ruby-1.9.3-p286@global/bin/ruby_noexec_wrapper:14:in `eval'
/Users/nate/.rvm/gems/ruby-1.9.3-p286@global/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by jspizziri** [comment]
@FineLineAutomation, was a PR ever submitted for this?

**Comment by FineLineAutomation** [comment]
Jacob,

I think I have the migration. Let me put it into  PR and then could you push to master, 2-4-stable, and 2-3-stable?

Regards,

Nate
Fine Line Automation
nate@finelineautomation.com

**Comment by jspizziri** [comment]
Sounds good, thanks!
