### ISSUE TITLE
Error: Unable to send the selected items to your delivery address elements. Please enter another delivery address

### ISSUE THREAD

**Issue by pamlicona** [spree-contrib/spree_active_shipping#207]
Hi,

I have a problem with gem spree_active_shipping. In the first step (address) the gem show me an error: "Unable to send the selected items to your delivery address elements. Please enter another delivery address". I don't know why?

And this is in the shell:

ActionController::RoutingError (No route matches [GET] "/assets/jquery.validate/localization/messages_es-MX.js"):
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/responsive/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /home/responsive/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /home/responsive/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

I installed the gem with: gem 'spree_active_shipping', git: 'git://github.com/spree/spree_active_shipping' and I made the instructions.

The zones configuration is correct.

Can you help me?

Thanks
Pamela Martínez

**Comment by jspizziri** [comment]
@pamlicona,

Please look at the [contributing guidelines](https://github.com/spree-contrib/spree_active_shipping/blob/master/CONTRIBUTING.md) and give us the steps to reproduce.
