### ISSUE TITLE
Can't run `bundle exec rake spree_sample:load` 

### ISSUE THREAD

**Issue by djsmentya** [spree-contrib/spree_active_shipping#260]
When i run `bundle exec rake spree_sample:load` task it fails on stock sample due to address validation.

**Comment by jspizziri** [comment]
@djsmentya,

Please include a the stack trace with this issue.

**Comment by djsmentya** [comment]
@jspizziri  here it is
```
$ bundle exec rake spree_sample:load

Loaded Payment Methods samples
Loaded Shipping Categories samples
Loaded Shipping Methods samples
Loaded Tax Categories samples
Loaded Tax Rates samples
Loaded Products samples
Loaded Taxonomies samples
Loaded Taxons samples
Loaded Option Types samples
Loaded Option Values samples
Loaded Product Option Types samples
Loaded Product Properties samples
Loaded Prototypes samples
Loaded Variants samples
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Address1 can't be blank, City can't be blank, Zipcode can't be blank, Country can't be blank, State name can't be blank
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/validations.rb:78:in `raise_validation_error'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/validations.rb:50:in `save!'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/transactions.rb:324:in `block in save!'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/transactions.rb:211:in `transaction'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/transactions.rb:324:in `save!'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.3/lib/active_record/suppressor.rb:45:in `save!'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/bundler/gems/spree-9ccde396a2d8/sample/db/samples/stock.rb:11:in `<top (required)>'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/bundler/gems/spree-9ccde396a2d8/sample/lib/spree/sample.rb:13:in `load_sample'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/bundler/gems/spree-9ccde396a2d8/sample/lib/spree_sample.rb:23:in `load_samples'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/bundler/gems/spree-9ccde396a2d8/sample/lib/tasks/sample.rake:20:in `block (2 levels) in <top (required)>'
/home/pair/work/dev-neokki/a-room/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/pair/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/pair/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
/home/pair/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
/home/pair/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/pair/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spree_sample:load

```

**Comment by jspizziri** [comment]
@djsmentya,

`spree_sample` is part of `Spree::Core` not part of this gem. Is there a reason that you're reporting the issue here? Your stack trace doesn't look like it's hitting this gem, and to my knowledge, this gem doesn't even contain any seed data.

**Comment by djsmentya** [comment]
@jspizziri when i remove `gem 'spree_active_shipping', github: 'spree-contrib/spree_active_shipping'` from my Gemfile all samples loads without errors

**Comment by jspizziri** [comment]
@djsmentya,

This gem require address1, city, etc. to be present on a stock location. See [here](https://github.com/spree-contrib/spree_active_shipping/blob/2db1aabac1238822f5d8b612a117db228a9642f0/app/models/spree/stock_location_decorator.rb).

It sounds like the seed data you're loading doesn't have that, which is generating the error. You'll have to fix the seed data to comply with the requirements of this gem so that you don't get the error.

**Comment by djsmentya** [comment]
@jspizziri Just created a clean rails app which allows to reproduce this issue. 
Steps to reproduce: 

```
git clone https://github.com/djsmentya/spree-error-test.git
cd spree-error-test
bundle install
bundle exec rake db:migrate
bundle exec rake db:seed
bundle exec rake spree_sample:load
```
